main [@tu @remains] = [[${tu}]]
textAndURL [@stuff uRef] = [[${uRef}]]
stuff [c] = [[${c}]]
urlRef [uref] = [[${uref}]]
referencesRef [klb kref krb klp @notRP krp] = [[]]
tocRef [klb ktoc krb klp @notRP krp] = [[]]
otherRef [klb @notRB krb klp @notRP krp] = [[${klb}${notRB}${krb}${klp}${notRP}${krp}\n]]
notRBracket [c] = [[${c}]]
notRPAR [c] = [[${c}]]
